import Head from "next/head";
import type { InferGetStaticPropsType } from "next";
import NepaliDate from "nepali-date-converter";
import { Article } from "@/components/articles.columns";
import Image from "next/image";
import { HomePageResponse } from "~/types";
import Navbar from "@/components/Navbar";

type PropType = InferGetStaticPropsType<typeof getStaticProps>;

export default function Home(props: PropType) {
  return (
    <>
      <Head>
        <title>Abiral Sanchar : Pathway To Enlightenment</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="https://fav.farm/📢" />
      </Head>


      <div className="flex flex-col p-4  items-center  sm:items-center md:text-center lg:pl-12 lg:items-start ">
        <div className="text-4xl font-extrabold">
          <Image src='https://www.abiralsanchar.com/_next/static/media/abiralsancharlogo.aa7052d0.svg'
            alt="Abiral Sanchar Logo" width={200} height={200}
          />
        </div>
        <div className="text-sm ">{new NepaliDate(new Date()).toString()}</div>
      </div>
<Navbar />
{props.posts.data[1]?.featured_articles?.map((category)=>(
  <div>
    {category.title}
  </div>
))}
    </>
  );
}

export async function getStaticProps() {
  const posts = await (
    await fetch("https://jsugauta1.pythonanywhere.com/api/v1/news/homepage/", {
      method: "GET",
    })
  ).json() as HomePageResponse

  console.log(posts)
  return {
    props: {
      posts,
    },

    revalidate: 10,
  };
}
