import Head from "next/head";
import type { InferGetStaticPropsType } from "next";
import NepaliDate from "nepali-date-converter";
import Image from "next/image";
import { HomePageResponse } from "~/types";
import Navbar from "@/components/Navbar";
import { ArrowRight, HistoryIcon, Menu, User, UserCircle } from "lucide-react";
import { formatDistanceToNow } from "date-fns";

import CategoryCarousel from "@/components/CategoryCarousel";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";

type PropType = InferGetStaticPropsType<typeof getStaticProps>;

export default function Home(props: PropType) {
  return (
    <>
      <Head>
        <title>Abiral Sanchar : Pathway To Enlightenment</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="https://fav.farm/📢" />
      </Head>

      <div className="flex flex-row items-center  justify-between  p-4  ">
        <div className="hamburger block md:hidden">
          <UserCircle />
        </div>
        <div className="text-4xl ">
          <Image
            src="https://www.abiralsanchar.com/_next/static/media/abiralsancharlogo.aa7052d0.svg"
            alt="Abiral Sanchar Logo"
            width={200}
            height={200}
          />
          <div className="text-base  text-center font-khand ">
            {new NepaliDate(new Date()).toString()}
          </div>
        </div>
        <div className="hamburger block md:hidden">
          <Sheet>
            <SheetTrigger asChild>
              <Menu className="hover:cursor-pointer" />
            </SheetTrigger>
            <SheetContent className="w-3/6">
              <div className="flex flex-col text-center">
                <div className=" text-2xl font-khand font-bold">
                  Abiral<span className="text-primary">Sanchar</span>
                </div>
              </div>
            </SheetContent>
          </Sheet>
        </div>
      </div>

      <div className="hidden md:block">

      <Navbar />
      </div>
      <div className=" flex flex-col items-center  mx-10   ">
        {props?.posts?.data[1]?.featured_articles?.map((news) => (
          <div
            key={news.id}
            className=" flex  w-full flex-col border-b py-2 text-center"
          >
            <div className="lg:text-5xl mt-2 text-2xl font-extrabold font-mono transition delay-150 duration-300 hover:cursor-pointer hover:text-primary md:text-3xl">
              {news.title} Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eius voluptates veritatis nulla doloremque voluptas repellat modi ut est quis, magni cumque dolor 
            </div>
            <div className="mt-2 flex">
              <div className="mx-auto flex items-center">
                <HistoryIcon className="mr-2" />
                {formatDistanceToNow(news.created_at)} ago
              </div>
            </div>
          </div>
        ))}
      </div>


<div className="flex flex-row">
<div className="font-khand text-3xl">समाचार</div>
</div>


      {/* <div className="bg-muted-foreground opacity-80  px-6 md:px-14 py-10 ">
        <div className="flex flex-row items-center justify-between">
          <div className="text-2xl font-bold text-secondary">Categories</div>
          <div className="text-2xl font-bold text-secondary">
            <ArrowRight />
          </div>
        </div>

        <CategoryCarousel posts={props.posts} />
      </div> */}
    </>
  );
}

export async function getStaticProps() {
  const posts = (await (
    await fetch("https://jsugauta1.pythonanywhere.com/api/v1/news/homepage/", {
      method: "GET",
    })
  ).json()) as HomePageResponse;

  return {
    props: {
      posts,
    },

    revalidate: 10,
  };
}
